Select/reset button for events
anucssa/anutimetable pull request #55
Opened 2022-01-14 12:43 UTC by OliverBalfour

2022-01-14 13:11 UTC, OliverBalfour commented
Only one regression I found: the agenda section has missing data. I've just fixed this

2022-01-14 22:34 UTC, pl4nty commented
I'm out this morning, but I'll get to this today, thanks Oliver! Would normally avoid global state/rerenders for performance and complexity, but seems fine here (even faster than the FC API anecdotally) and I don't see the state growing too much.

2022-01-15 03:15 UTC, pl4nty requested changes
Not sure how I feel about the state handling, but it works and the rest is great so I'm happy.

2022-01-15 03:15 UTC, pl4nty commented on src/Export.js
> +      href={`https://www.google.com/calendar/render?cid=${encodeURIComponent(webcal.replace('https', 'http'))}`}>
Dug a bit deeper and I'll need to refactor the link generation (to fix Exchange/Outlook), but I'll do that in another branch

2022-01-15 03:15 UTC, pl4nty commented on src/Toolbar.js
> +  timeZone, year, session, sessions, JSON, modules, selectedModules,
```suggestion
  timeZone, year, session, sessions, timetableData, modules, selectedModules,
```

2022-01-15 03:15 UTC, pl4nty commented on src/Toolbar.js
> +  setTimeZone, setYear, setSession, setSessions, setJSON, setModules, setSelectedModules,
```suggestion
  setTimeZone, setYear, setSession, setSessions, setTimetableData, setModules, setSelectedModules,
```

2022-01-15 03:15 UTC, pl4nty commented on src/Calendar.js
> +        eventContent: e => formatEventContent(state)(e)
```suggestion
        ...customEvents
```

2022-01-15 03:15 UTC, pl4nty commented on src/App.js
> +    <Calendar API={API} ref={calendar} state={state} />
```suggestion
    <Calendar ref={calendar} state={state} />
```

2022-01-15 03:22 UTC, OliverBalfour commented on src/index.css
>  .fc .fc-event a {
If they're using links internally, perhaps? As we're forcing the color to be inherited we can always change the bootstrap button's parent's color but that's a little nasty I suppose

2022-01-15 03:26 UTC, OliverBalfour commented on src/Calendar.js
> +      ? <button className='choose-button' onClick={() => dispatch(selectOccurrence)}>Choose</button>
I prefer the text link buttons because sometimes the background colour clashes with the button colour - thoughts?

2022-01-15 03:28 UTC, pl4nty commented
Interesting bug with the text overflow, also affects buttons

![image](https://user-images.githubusercontent.com/21111317/149607245-0a22888c-9d1a-465e-8452-1404bb97cbd6.png)

2022-01-15 03:28 UTC, OliverBalfour commented
Re: state handling, the reason I moved everything into App was because a lot of stuff didn't make sense inside Toolbar, eg which events are selected, and I needed a way to propagate that info into the Calendar. The state handling is not ideal, I agree, I only did precisely enough refactoring to enable me to pass the state where it was needed, but didn't clean it up afterwards.

Virtually all of the state handling code is the same or very similar, it's just been moved and is all passed down

2022-01-15 03:31 UTC, OliverBalfour commented
> Interesting bug with the text wrapping, also affects buttons
> 
> ![image](https://user-images.githubusercontent.com/21111317/149607245-0a22888c-9d1a-465e-8452-1404bb97cbd6.png)

Good catch, just fixed (missing `overflow-y: hidden`)

2022-01-15 03:34 UTC, pl4nty commented
All good, originally I stored all user input in the toolbar (and using the calendar ref just to display), but that fell apart when the calendar itself took input. Glad we're on the same page, not ideal as-is but a big improvement on what I had, and enough to release to users.

2022-01-15 03:34 UTC, pl4nty commented
Nice! TIL that exists

2022-01-15 03:37 UTC, OliverBalfour commented
Thinking about the state management, the main reason it's ugly is because CalendarApi is imperative and doesn't let you pass an events list prop. Longer term, I might make a FullCalendar wrapper that simply adds an `events` prop that wrangles CalendarApi for you. Then the only complex bits is generating the list of events to pass via props - that's most of the contents of the giant `useEffect` - but it could be moved to a helper function in `Calendar.js` when we can pass events as a prop

2022-01-15 03:39 UTC, pl4nty commented
ahhhhh, I thought FC was imperative? never tested cause I was attempting to wrangle the API, which was a poor choice in hindsight. https://fullcalendar.io/docs/initialEvents

2022-01-15 03:43 UTC, OliverBalfour commented
> ahhhhh, I thought FC was imperative? never tested cause I was attempting to wrangle the API, which was a poor choice in hindsight. https://fullcalendar.io/docs/initialEvents

Yeah what I'm proposing is a wrapper that makes a prop like `initialEvents`, except it actually *does* update the events when the prop changes. It'd be a separate file that does some funky stuff with effects to translate changes to the prop into `CalendarApi` calls, so it abstracts away the imperative-ness and presents a declarative API

Edit: see your edit now, gotcha

2022-01-15 03:46 UTC, pl4nty commented on src/Calendar.js
> +      ? <button className='choose-button' onClick={() => dispatch(selectOccurrence)}>Choose</button>
Agreed, I'm testing locally to see if the -outline variants or links fix that. Happy to merge and PR button stuff later.

2022-01-15 03:48 UTC, pl4nty commented on src/index.css
>  .fc .fc-event a {
Will test this, variant=link uses links internally but I'm sure there's a way to exclude them

2022-01-15 03:50 UTC, pl4nty commented
Yeah - I think the default events prop (eg https://fullcalendar.io/docs/events-array) is declarative, and initialEvents is imperative for those that want it

2022-01-15 03:55 UTC, pl4nty approved these changes
LGTM ❤

2022-01-15 03:56 UTC, merged