Add Dark Mode and Dark Mode Toggle Button
anucssa/anutimetable pull request #68
Opened 2022-01-15 13:58 UTC by ashleylamont

No longer shall poor innocent uni students writing timetables in the dead hours of the morning be exposed to the horrors of a white background. 🌙☀️😎
![cat-blind-flashbang-light-mode](https://user-images.githubusercontent.com/59380148/149624287-4c642d37-678f-44bc-82ec-0209ecb20b0c.gif)

2022-01-15 15:58 UTC, pl4nty requested changes
Ayyy I almost wrote a PoC with bootstrap-darkmode but couldn't get it done in time, nice! That fab really helps with keeping the UI clean while adding features too.

Just a few bugs I found:
![image](https://user-images.githubusercontent.com/21111317/149628482-6da0366a-be25-44b5-965e-15be330253f2.png)

![image](https://user-images.githubusercontent.com/21111317/149628546-a645f2c9-3a36-4eef-be82-2861937999f4.png)

(agenda view)
![image](https://user-images.githubusercontent.com/21111317/149628513-7f5cc72c-89b9-4dbc-a301-5f2285ecdf4b.png)

2022-01-16 01:02 UTC, OliverBalfour commented
Also, pressing the dark/light toggle should probably close the FAB

2022-01-16 01:16 UTC, ashleylamont commented
@OliverBalfour I don't agree with that, for something where it directly opens another menu or performs a clear action (like creating a new event or something) sure, but for what is ostensibly a toggle button, I don't think it should close the menu. I might look into adding a mouseout check later though to close it if the user leaves the menu instead.

2022-01-16 01:20 UTC, pl4nty commented
I think I agree with you @ashleylamont, keeping it open while toggling is nice to show/hide the difference. but clicking off should be good to close since the user is returning to the app - could this apply to all menu components, like the dropdown? currently have to click the close button, instead of clicking outside the popup

2022-01-16 01:24 UTC, ashleylamont commented
Not sure, other menu components would be implemented by the react-bootstrap library I presume? I did this one as something of a DIY operation since FABs are technically MD spec rather then Bootstrap spec, but I'm quite fond of them. It's possible for the other components, but short of modifying the component in the library or making a new one, rather troublesome, as we can't easily modify the underlying component.

2022-01-16 01:29 UTC, pl4nty commented
sorry, "all menu components" was just referring to all FAB components

2022-01-16 01:30 UTC, ashleylamont commented
Ah gotcha, you mean the dialog then I take it? If so then yeah definitely, I probably should have done that before actually 😅

2022-01-17 09:06 UTC, ashleylamont commented
@pl4nty those bits should be fixed now

2022-01-17 09:16 UTC, ashleylamont commented
> Azure Static Web Apps: Your stage site is ready! Visit it here: https://yellow-cliff-008e54a00-68.eastasia.azurestaticapps.net

Might need to force/hard refresh to get it to reload the stylesheet btw ;)

2022-01-17 09:19 UTC, pl4nty approved these changes
Brilliant, thanks Ashley!

2022-01-17 09:23 UTC, merged

2022-01-17 09:25 UTC, pl4nty commented
Whoops, don't mind the co-authored-by - the squash commit shows you as the author, as it should